//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "BareEthernetPinout.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/rom_map.h"
#include "driverlib/gpio.h"

//*****************************************************************************
void
PortFunctionInit(void)
{
    //
    // Enable Peripheral Clocks 
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_EPHY0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_EMAC0);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOG);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOH);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOK);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOP);

    //
    // Enable pin PG0 for EMAC0 EN0PPS
    //
    MAP_GPIOPinConfigure(GPIO_PG0_EN0PPS);
    MAP_GPIOPinTypeEthernetMII(GPIO_PORTG_BASE, GPIO_PIN_0);

    //
    // Enable pin PF1 for EPHY0 EN0LED2
    //
    MAP_GPIOPinConfigure(GPIO_PF1_EN0LED2);
    MAP_GPIOPinTypeEthernetLED(GPIO_PORTF_BASE, GPIO_PIN_1);

    //
    // Enable pin PF0 for EPHY0 EN0LED0
    //
    MAP_GPIOPinConfigure(GPIO_PF0_EN0LED0);
    MAP_GPIOPinTypeEthernetLED(GPIO_PORTF_BASE, GPIO_PIN_0);

    //
    // Enable pin PF4 for EPHY0 EN0LED1
    //
    MAP_GPIOPinConfigure(GPIO_PF4_EN0LED1);
    MAP_GPIOPinTypeEthernetLED(GPIO_PORTF_BASE, GPIO_PIN_4);

    //
    // Enable pin PK7 for UART0 U0RI
    //
    MAP_GPIOPinConfigure(GPIO_PK7_U0RI);
    MAP_GPIOPinTypeUART(GPIO_PORTK_BASE, GPIO_PIN_7);

    //
    // Enable pin PB5 for UART0 U0RTS
    //
    MAP_GPIOPinConfigure(GPIO_PB5_U0RTS);
    MAP_GPIOPinTypeUART(GPIO_PORTB_BASE, GPIO_PIN_5);

    //
    // Enable pin PA1 for UART0 U0TX
    //
    MAP_GPIOPinConfigure(GPIO_PA1_U0TX);
    MAP_GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_1);

    //
    // Enable pin PP2 for UART0 U0DTR
    //
    MAP_GPIOPinConfigure(GPIO_PP2_U0DTR);
    MAP_GPIOPinTypeUART(GPIO_PORTP_BASE, GPIO_PIN_2);

    //
    // Enable pin PA0 for UART0 U0RX
    //
    MAP_GPIOPinConfigure(GPIO_PA0_U0RX);
    MAP_GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0);

    //
    // Enable pin PB4 for UART0 U0CTS
    //
    MAP_GPIOPinConfigure(GPIO_PB4_U0CTS);
    MAP_GPIOPinTypeUART(GPIO_PORTB_BASE, GPIO_PIN_4);

    //
    // Enable pin PH2 for UART0 U0DCD
    //
    MAP_GPIOPinConfigure(GPIO_PH2_U0DCD);
    MAP_GPIOPinTypeUART(GPIO_PORTH_BASE, GPIO_PIN_2);

    //
    // Enable pin PH3 for UART0 U0DSR
    //
    MAP_GPIOPinConfigure(GPIO_PH3_U0DSR);
    MAP_GPIOPinTypeUART(GPIO_PORTH_BASE, GPIO_PIN_3);
}
